-- MySQL Script generated by MySQL Workbench
-- Sat Oct 26 16:52:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `idFlight` INT(8) NOT NULL,
  `departure` TIMESTAMP(1) NOT NULL,
  `arrival` TIMESTAMP(1) NOT NULL,
  PRIMARY KEY (`idFlight`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `idPassenger` INT(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Flight_idFlight` TINYINT(8) NOT NULL,
  PRIMARY KEY (`idPassenger`),
  INDEX `fk_Passenger_Flight1_idx` (`Flight_idFlight` ASC) VISIBLE,
  CONSTRAINT `fk_Passenger_Flight1`
    FOREIGN KEY (`Flight_idFlight`)
    REFERENCES `mydb`.`Flight` (`idFlight`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `idAirport` TINYINT(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAirport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BaggageClaim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BaggageClaim` (
  `idBaggageClaim` TINYINT(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Airport_idAirport` INT NOT NULL,
  PRIMARY KEY (`idBaggageClaim`),
  INDEX `fk_BaggageClaim_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  CONSTRAINT `fk_BaggageClaim_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Luggage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Luggage` (
  `idLuggage` INT(4) NOT NULL,
  `Flight_idFlight` TINYINT(8) NOT NULL,
  `BaggageClaim_idBaggageClaim` TINYINT(4) NOT NULL,
  `Passenger_idPassenger` INT(4) NOT NULL,
  PRIMARY KEY (`idLuggage`),
  INDEX `fk_Luggage_Flight1_idx` (`Flight_idFlight` ASC) VISIBLE,
  INDEX `fk_Luggage_BaggageClaim1_idx` (`BaggageClaim_idBaggageClaim` ASC) VISIBLE,
  INDEX `fk_Luggage_Passenger1_idx` (`Passenger_idPassenger` ASC) VISIBLE,
  CONSTRAINT `fk_Luggage_Flight1`
    FOREIGN KEY (`Flight_idFlight`)
    REFERENCES `mydb`.`Flight` (`idFlight`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Luggage_BaggageClaim1`
    FOREIGN KEY (`BaggageClaim_idBaggageClaim`)
    REFERENCES `mydb`.`BaggageClaim` (`idBaggageClaim`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Luggage_Passenger1`
    FOREIGN KEY (`Passenger_idPassenger`)
    REFERENCES `mydb`.`Passenger` (`idPassenger`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilot` (
  `idPilot` TINYINT(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Flight_idFlight` INT(8) NULL,
  PRIMARY KEY (`idPilot`),
  INDEX `fk_Pilot_Flight1_idx` (`Flight_idFlight` ASC) VISIBLE,
  CONSTRAINT `fk_Pilot_Flight1`
    FOREIGN KEY (`Flight_idFlight`)
    REFERENCES `mydb`.`Flight` (`idFlight`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` TINYINT(4) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `idTicket` INT NOT NULL,
  `Company_idCompany` TINYINT(4) NOT NULL,
  `Passenger_idPassenger` INT(4) NULL,
  PRIMARY KEY (`idTicket`),
  INDEX `fk_Ticket_Company1_idx` (`Company_idCompany` ASC) VISIBLE,
  INDEX `fk_Ticket_Passenger1_idx` (`Passenger_idPassenger` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ticket_Passenger1`
    FOREIGN KEY (`Passenger_idPassenger`)
    REFERENCES `mydb`.`Passenger` (`idPassenger`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airplane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airplane` (
  `idAirplane` TINYINT(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Company_idCompany` TINYINT(4) NOT NULL,
  `Flight_idFlight` INT(8) NULL,
  PRIMARY KEY (`idAirplane`),
  INDEX `fk_Airplane_Company1_idx` (`Company_idCompany` ASC) VISIBLE,
  INDEX `fk_Airplane_Flight1_idx` (`Flight_idFlight` ASC) VISIBLE,
  CONSTRAINT `fk_Airplane_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Airplane_Flight1`
    FOREIGN KEY (`Flight_idFlight`)
    REFERENCES `mydb`.`Flight` (`idFlight`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gate` (
  `idGate` TINYINT(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Airplane_idAirplane` TINYINT(4) NULL,
  `Airport_idAirport` INT NOT NULL,
  PRIMARY KEY (`idGate`),
  INDEX `fk_Gate_Airplane1_idx` (`Airplane_idAirplane` ASC) VISIBLE,
  INDEX `fk_Gate_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  CONSTRAINT `fk_Gate_Airplane1`
    FOREIGN KEY (`Airplane_idAirplane`)
    REFERENCES `mydb`.`Airplane` (`idAirplane`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Gate_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmlpoyee` INT NOT NULL,
  PRIMARY KEY (`idEmlpoyee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hires` (
  `Pilot_idPilot` TINYINT(4) NOT NULL,
  `Company_idCompany` TINYINT(4) NOT NULL,
  `hire_id` INT(8) NOT NULL,
  PRIMARY KEY (`Pilot_idPilot`, `Company_idCompany`, `hire_id`),
  INDEX `fk_Pilot_has_Company_Company1_idx` (`Company_idCompany` ASC) VISIBLE,
  INDEX `fk_Pilot_has_Company_Pilot1_idx` (`Pilot_idPilot` ASC) VISIBLE,
  CONSTRAINT `fk_Pilot_has_Company_Pilot1`
    FOREIGN KEY (`Pilot_idPilot`)
    REFERENCES `mydb`.`Pilot` (`idPilot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pilot_has_Company_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employment` (
  `Employee_idEmployee` INT NOT NULL,
  `Airport_idAirport` TINYINT(4) NOT NULL,
  `idEmployment` INT(8) NOT NULL,
  PRIMARY KEY (`Employee_idEmployee`, `Airport_idAirport`, `idEmployment`),
  INDEX `fk_Employee_has_Airport_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  INDEX `fk_Employee_has_Airport_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_has_Airport_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `mydb`.`Employee` (`idEmlpoyee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Employee_has_Airport_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
